<a href="https://colab.research.google.com/github/DeeMastah/Linear-Algebra-58019/blob/main/Final_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import numpy as np
from numpy.linalg import eig

Problem 1. Student A, Student B, and Student C have a total of Php 89 cash in their banks. Student A has 6 less than Student C. Student B has 3 times what Student C has. How much does each student have? (30 points)

In [31]:
A = np.array([[1,1,1],[1,0,4],[0,0,5]]) #Creates the 3x3 matrix 
B = np.array([[89],[89],[95]]) #Creates the matrix from the right hand side 

print("Matrix A:")
print(A) #Prints out Matrix A
print("\nMatrix B:")
print(B) #Prints out Matrix B

print("\nAnswer:")
X = np.linalg.inv(A).dot(B)
print(X)

Matrix A:
[[1 1 1]
 [1 0 4]
 [0 0 5]]

Matrix B:
[[89]
 [89]
 [95]]

Answer:
[[13.]
 [57.]
 [19.]]


Problem 2. Solve each system: (30 points)

3x - y + z = 5

9x - 3y +3z = 15

-12x +4y -4z = -20 

In [28]:
A = np.array([[3,-1,1],[9,-3,3],[-12,4,-4]]) #Creates the 3x3 matrix from the system of equations
print(A)#Prints the matrix

B = np.array([[5],[15],[-20]]) #Creates the matrix from the right hand side of the systems
print (B)#Prints the matrix

Apinv = np.linalg.pinv(A) #Computes for the pseudo inverse of A
x = Apinv.dot(B) # apply the pseudo-inverse to the right hand side vector to get the solution

print("\nSolution:")
print(x) #Displays the solution
 

[[  3  -1   1]
 [  9  -3   3]
 [-12   4  -4]]
[[  5]
 [ 15]
 [-20]]

Solution:
[[ 1.36363636]
 [-0.45454545]
 [ 0.45454545]]


Problem 3. Consider the matrix, (40 points) 

In [8]:
X = np.array([[8,5,-6],[-12,-9,12],[-3,-3,5]]) #Creates a 3x3 Matrix

print("3x3 Matrix: ")
print(X,"\n") #Prints the matrix

w,v = np.linalg.eig(X)  #The eig method to get the eigenvalue and eigenvector
print("The eigenvalues are:\n",w.round(),"\n")#Displays the eigenvalues
print("The eigenvectors are:\n",v.round())#Displays the eigenvectors

3x3 Matrix: 
[[  8   5  -6]
 [-12  -9  12]
 [ -3  -3   5]] 

The eigenvalues are:
 [-1.  3.  2.] 

The eigenvectors are:
 [[ 0. -1.  1.]
 [-1.  1.  0.]
 [-0. -0.  1.]]
