<a href="https://colab.research.google.com/github/DeeMastah/Linear-Algebra-58019/blob/main/Matrix_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np 

In [5]:
A = np.array ([[1,2],[4,7]])

invA = np.linalg.inv(A) #Inverse of Matrix A

print(invA)

[[-7.  2.]
 [ 4. -1.]]


In [6]:
C = np.dot(A, invA) #Get identity matrix
print(C)

[[1. 0.]
 [0. 1.]]


In [12]:
A = np.array ([[6,1,1],[4,-2,5],[2,8,7]])

InvOfA = np.linalg.inv(A) #To inverse Matrix A

print(A)

B = np.transpose(A) #To transpose Matrix A

print (B)

[[ 6  1  1]
 [ 4 -2  5]
 [ 2  8  7]]
[[ 6  4  2]
 [ 1 -2  8]
 [ 1  5  7]]


In [13]:
dot = np.dot(A, InvOfA) #Get dot product of A and its inverse

print(dot)

[[ 1.00000000e+00  0.00000000e+00  2.77555756e-17]
 [-1.38777878e-17  1.00000000e+00  1.38777878e-17]
 [-4.16333634e-17  1.38777878e-16  1.00000000e+00]]


#Coding Activity 3

Create a Python Program to inverse and transpose a 4x4 matrix,
A = ( [6,1,1,3],[4,-2,5,1],[2,8,7,6],[3,1,9,7] )

In [14]:
A = np.array([[6,1,1,3],[4,-2,5,1],[2,8,7,6],[3,1,9,7]])

InvOfA = np.linalg.inv(A) #To inverse Matrix A

print(A)

B = np.transpose(A) #To transpose Matrix A

print (B)

[[ 6  1  1  3]
 [ 4 -2  5  1]
 [ 2  8  7  6]
 [ 3  1  9  7]]
[[ 6  4  2  3]
 [ 1 -2  8  1]
 [ 1  5  7  9]
 [ 3  1  6  7]]
