<a href="https://colab.research.google.com/github/DeeMastah/Linear-Algebra-58019/blob/main/Midterm_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

Question 1. Create a Python code that displays a square matrix whose length is 5 

In [38]:
#Sets the size of the matrix
size = (5,5)  
#Creates a square matrix whose length is 5
square_matrix = np.zeros(size)

#Prints a square matrix whose length is 5
print('A square matrix with a length of 5')
print(square_matrix)


A square matrix with a length of 5
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


Question 2. Create a Python code that displays a square matrix whose elements below the principal diagonal are zero

In [43]:
#Creates a square matrix whose elements below the principal diagonal are zero
square_matrix = np.array([[1,2,3,4,5],
                          [0,1,2,3,4],
                          [0,0,1,2,3],
                          [0,0,0,1,2],
                          [0,0,0,0,1]])

#Prints a square matrix whose elements below the principal diagonal are zero
print('A square matrix whose elements below the principal diagonal are zero')
print(square_matrix)

A square matrix whose elements below the principal diagonal are zero
[[1 2 3 4 5]
 [0 1 2 3 4]
 [0 0 1 2 3]
 [0 0 0 1 2]
 [0 0 0 0 1]]


Question 3. Create a Python code that displays a square matrix which is symmetrical

In [44]:
#Creates a square matrix  which is symmetrical
square_matrix = np.array([[1,2,3,4,5],
                          [2,1,2,3,4],
                          [3,2,1,2,3],
                          [4,3,2,1,2],
                          [5,4,3,2,1]])

#Prints a square matrix which is symmetrical
print('A square matrix which is symmetrical')
print(square_matrix)

A square matrix hich is symmetrical
[[1 2 3 4 5]
 [2 1 2 3 4]
 [3 2 1 2 3]
 [4 3 2 1 2]
 [5 4 3 2 1]]


Question 4. What is the inverse of matrix C? Show your solution by python coding.

In [27]:
C = np.array ([[1,2,3],
               [2,3,3],
               [3,4,-2]])

#Gets the inverse of Matrix C
invC = np.linalg.inv(C)

#Prints the inverse of Matrix C
print("Inverse of Matrix C:")
print(invC)

Inverse of Matrix C:
[[-3.6  3.2 -0.6]
 [ 2.6 -2.2  0.6]
 [-0.2  0.4 -0.2]]


Question 5. What is the determinant of the given matrix in Question 4? Show your solution by python coding. (20 points)

In [10]:
C = np.array ([[1,2,3],
               [2,3,3],
               [3,4,-2]])
#Gets the determinant of the given matrix in question 4
detOfC = np.linalg.det(C)

#Prints the determinant of the given matrix in question 4
print("Determinant of the given matrix in Question 4:")
print(int(detOfC))

Determinant of the given matrix in Question 4:
5


Question 6. Find the roots of the linear equations by showing its python codes (30 points)

5X1 + 4X2 + X3 = 3.4

10X1 + 9X2 + 4X3 = 8.8

10X1 + 13X2 + 15X3 = 19.2

In [16]:
eq = np.array([[5,4,1],
               [10,9,4],
               [10,13,15]])

const = np.array([[[3.4],
                   [8.8],
                   [19.2]]])

#Gets the root of the given linear equations
roots = np.linalg.inv(eq) @ const

#Prints the root of the given linear equations
print("Roots of the given linear equations:")
print(roots)

Roots of the given linear equations:
[[[0.2]
  [0.4]
  [0.8]]]
