<a href="https://colab.research.google.com/github/DeeMastah/Linear-Algebra-58019/blob/main/Practical_Lab_Exam_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [21]:
import numpy as np
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[1,2],[3,4],[5,6]]) 
C = np.array([[1,2,3],[4,5,6],[7,8,9]])
D = np.array([[1,2],[3,4]]) 

a = np.dot(A,B)
b = np.add(D,D)
c = 2*C

print("Problem 1\n\nA.")
print(a)
print("\nB.")
print(b)
print("\nC.")
print(c)


Problem 1

A.
[[22 28]
 [49 64]]

B.
[[2 4]
 [6 8]]

C.
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [24]:
import numpy as np
X = np.array([5,3,-1])

print("Problem 2\n\nCorresponding matrix to θ = 5x + 3y -z")
print(X)
#Type
print("\nType:")
print(type(X))
#Dimension
print("\nDimension:")
print(X.ndim)
#Shape
print("\nShape:")
print(X.shape)
#Size
print("\nSize:")
print(X.size)

Problem 2

Corresponding matrix to θ = 5x + 3y -z
[ 5  3 -1]

Type:
<class 'numpy.ndarray'>

Dimension:
1

Shape:
(3,)

Size:
3
